### ISSUE TITLE
Compiled module breaks IE11

### ISSUE THREAD

**Issue by Cottin** [robrichard/graphql-fields#7]
Maybe not what `graphql-fields` was intended for, but I'm using it client-side to do some custom automised caching logic on top of apollo.

package.json:
```
  "dependencies": {
    "graphql-fields": "^1.0.2",

```

.babelrc:
```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions"]
      },
```
=> [IE11 and IE10 should be supported by jun 2018](http://browserl.ist/?q=last+2+versions)

node_modules/graphql-fields/index.js contains for instance an arrow function here:
```
return fields.reduce((o, ast) => {
            return flattenAST(ast, info, o);
```
...which gets inserted into bundle.js when using webpack and causes IE11 to break with a nice "Syntax error".

I don't know if you want to support this by compiling graqhql-fields to es5 but I just spent some time debugging this to figure out why a project didn't work in IE so I just thought I'd mention it ;)

**Comment by robrichard** [comment]
I think it’s fair to support the same set of browsers supported by graphql-js. Can you open a PR to add the build step?

**Comment by nicolas-marien** [comment]
Hello. Thank you for this module. On IE11 the arrow function will not be the only issue, since IE11 does not support `Object.assign`. @robrichard would you be okay w/ a prepublish task running babel w/ present env as @Cottin suggests and also [this transform](https://www.npmjs.com/package/babel-plugin-transform-object-assign) to tackle the `assign` thing ?

**Comment by robrichard** [comment]
@nico29 yes I would be ok with merging a PR that adds that.

**Comment by nicolas-marien** [comment]
@robrichard Okay, I'll submit a PR addressing in during the weekend :)
